# Main composition file for SIG Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3.8'
services:

   # First Sig application container.
  puppetserver:
    container_name: puppet-server
    # Map container ports to puppet service:
    ports:
      - "8140:8140"
    # Map container volumes to puppet container:
    volumes:
      - "./config/hosts:/etc/hosts"
     # - "./config/puppetserver:/etc/default/puppetserver"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
